### ISSUE TITLE
User can add a Daily To-do list

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

A User will be able to create a "To-do list" of tasks to follow daily as they live their island life.
Dailies can include hitting rocks, talking to villagers, checking the shore for washed up bottles, and checking out Kapp'n islands.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to add tasks to an unorganized list where they can checkoff when the task is complete.
They will be able to edit tasks once added onto the list. When editing a task, they also have an option to delete the task if necessary.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-01-05 124201](https://user-images.githubusercontent.com/93615301/148286545-dca136cb-27c2-49d1-a806-f6be26b91ca7.jpg)
![Screenshot 2022-01-05 124236](https://user-images.githubusercontent.com/93615301/148286580-f797b9cd-fe4b-4a36-b8cc-6dfb4f3c006f.jpg)
![Screenshot 2022-01-05 124253](https://user-images.githubusercontent.com/93615301/148286594-c531a6a5-e94f-4820-bbfa-1d59cf6a5975.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Start with creating the `<nav>` bar at the top of the page.
- [x] Add a `<a>` for the tabs: "Daily Tasks", "Collection", "Happy Home Network Photos", and "Stalk Market".
- [x] Add `<h1>` for "Daily Tasks"
- [x] Add `<p>` for when there is no tasks added stating "No tasks have been added yet for today."
- [x] Add CSS to center no tasks message
- [x] Create a new empty `<ul>`
- [x] Add some false tasks with `<li>`
- [x] For each `<li>`, add a check box to indicate whether it is complete.
- [x] Add an icon to indicate editing.
- [x] Add an icon to act as bullet point.
- [x] Throw bullet point and task text in one div.
- [x] Throw Checkbox and edit icon in one div.
- [x] Add CSS  flex rules to separate task/bullet point away from checkbox/edit icon.
- [x] Create a new `<button>` for adding new task item.
- [x] Create a new `<form>` for adding on a new task
- [x] Within the form, create an `<input>` for the task
- [x] Add a `<button>` for submitting the new task.
- [x] The submitted task is then saved to local storage
- [x] Create a new function that would create a new DOM tree for the task
- [x] Within the function, have it so it adds on the new DOM tree to the `<ul>` task list
- [x] Add to function that would have the `<p>` indicating there are no tasks changing its class to disappear when there are tasks available
- [x] Add a function/CSS to hide or pop out add task form.
- [x] Create a function for when edit button is pressed, a new form shows up on the page
- [x] Within the form contains the task already in the input
- [x] Within the form are two buttons for either saving the newly edited task or deleting
- [x] When saved, the form closes and the edited task appears within the DOM tree as it was edited.
- [x] When deleted, the form closes and the task is deleted from both the list and local storage
- [x] When in mobile view, add CSS to hide nav bar.
- [x] Add a function for nav bar to pop out side with links to different features.
- [x] Add function to make add task button disappear when either add form or edit form is up.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
